export const hardwareProducts = [
  {
    id: 'wooting-60he',
    name: 'Wooting 60HE+',
    category: 'Keyboard',
    brand: 'Wooting',
    image: '/reviews/wooting-60he.webp',
    alt: 'Wooting 60HE+ black keyboard with its yellow Take Control strap',
    description:
      'A compact analog keyboard built around adjustable actuation and Rapid Trigger.',
    details: [
      ['Layout', '60%'],
      ['Switches', 'Lekker magnetic'],
    ],
    url: 'https://wooting.io/wooting-60he',
  },
  {
    id: 'finalmouse-ulx',
    name: 'Finalmouse ULX Phantom',
    category: 'Mouse',
    brand: 'Finalmouse',
    image: '/reviews/finalmouse-ulx-light-cutout.webp',
    alt: 'Finalmouse UltralightX Phantom mouse viewed from above',
    description:
      'The Phantom edition of Finalmouse’s UltralightX gaming mouse.',
    details: [
      ['Series', 'UltralightX'],
      ['Edition', 'Phantom'],
    ],
    url: 'https://finalmouse.com/pages/mice',
  },
  {
    id: 'sennheiser-hd6xx',
    name: 'Sennheiser HD 6XX',
    category: 'Headphones',
    brand: 'Sennheiser × Massdrop',
    image: '/reviews/sennheiser-hd6xx-cutout.webp',
    alt: 'Sennheiser HD 6XX over-ear headphones in midnight blue',
    description:
      'A community collaboration from the HD 600 family, finished in midnight blue.',
    details: [
      ['Cable', 'Detachable · 1.8 m'],
      ['Connector', '3.5 mm + 6.35 mm adapter'],
    ],
    url: 'https://us.sennheiser-hearing.com/products/hd-6xx',
  },
  {
    id: 'wallhack-sp004',
    name: 'WALLHACK SP-004',
    category: 'Mousepad',
    brand: 'WALLHACK',
    image: '/reviews/skypad-sp004.png',
    alt: 'Black WALLHACK SP-004 glass mousepad viewed from above',
    description: 'A micro-etched glass surface with a full silicone base.',
    details: [
      ['Surface', 'Silicate glass'],
      ['Dimensions', '490 × 430 × 3.9 mm'],
    ],
    url: 'https://wallhack.com/products/sp-004-black',
  },
  {
    id: 'jds-atom-2',
    name: 'JDS Labs Atom 2 Stack',
    category: 'Amp + DAC',
    brand: 'JDS Labs',
    image: '/reviews/jds-atom-2-cutout.webp',
    alt: 'JDS Labs Atom Amp 2 and Atom DAC 2 desktop audio stack',
    description:
      'A desktop audio pair combining the Atom Amp 2 headphone amplifier and Atom DAC 2.',
    details: [
      ['Amplifier', 'Atom Amp 2'],
      ['DAC', 'Atom DAC 2'],
    ],
    url: 'https://jdslabs.com/product/atom-amp-2/',
  },
  {
    id: 'iphone-17-pro',
    name: 'iPhone 17 Pro',
    category: 'Phone',
    brand: 'Apple',
    image: '/reviews/iphone-17-pro-silver.webp',
    alt: 'Silver Apple iPhone 17 Pro',
    description:
      'Apple’s Pro iPhone, with a triple-camera system and an aluminum unibody design.',
    details: [
      ['Family', 'iPhone 17'],
      ['Finish', 'Silver'],
    ],
    url: 'https://www.apple.com/newsroom/2025/09/apple-unveils-iphone-17-pro-and-iphone-17-pro-max/',
  },
  {
    id: 'dt-990-pro',
    name: 'Beyerdynamic DT 990 Pro',
    category: 'Headphones',
    brand: 'Beyerdynamic',
    image: '/reviews/dt-990-pro.png',
    alt: 'Beyerdynamic DT 990 Pro open-back headphones',
    description:
      'Open-back studio headphones with an over-ear fit and replaceable ear pads.',
    details: [
      ['Design', 'Open-back'],
      ['Fit', 'Over-ear'],
    ],
    url: 'https://north-america.beyerdynamic.com/p/dt-990-pro',
  },
  {
    id: 'ikea-idasen',
    name: 'IKEA IDÅSEN',
    category: 'Desk',
    brand: 'IKEA',
    image: '/reviews/ikea-idasen-black.webp',
    alt: 'IKEA IDÅSEN desk with a black tabletop and dark gray legs',
    description: 'A workspace desk from IKEA’s IDÅSEN office furniture series.',
    details: [
      ['Series', 'IDÅSEN'],
      ['Finish', 'Black / dark gray'],
    ],
    url: 'https://www.ikea.com/us/en/cat/idasen-system-47424/',
  },
  {
    id: 'steelcase-leap',
    name: 'Steelcase Leap V2',
    category: 'Chair',
    brand: 'Steelcase',
    image: '/reviews/steelcase-leap-black.webp',
    alt: 'Black Steelcase Leap V2 office chair',
    description:
      'An adjustable office chair with a flexible backrest designed to follow your movement.',
    details: [
      ['Model', 'Leap V2'],
      ['Finish', 'Black'],
    ],
    url: 'https://www.steelcase.com/products/office-chairs/leap/',
  },
  {
    id: 'macbook-pro-m5',
    name: 'MacBook Pro M5',
    category: 'Laptop',
    brand: 'Apple',
    image: '/reviews/macbook-pro-space-black-cutout.png',
    alt: 'Space Black Apple 14-inch MacBook Pro with M5, viewed from the front',
    description: 'The 14-inch MacBook Pro powered by Apple’s M5 chip.',
    details: [
      ['Chip', 'Apple M5'],
      ['Display', '14-inch Liquid Retina XDR'],
    ],
    url: 'https://www.apple.com/newsroom/2025/10/apple-unveils-new-14-inch-macbook-pro-powered-by-the-m5-chip/',
  },
  {
    id: 'arc-pulse',
    name: 'Arc Pulse',
    category: 'Phone case',
    brand: 'Arc',
    image: '/reviews/arc-pulse-silver.webp',
    alt: 'Silver Arc Pulse bumper case fitted to an iPhone 17 Pro',
    description:
      'A minimal two-piece phone case that leaves the back of the iPhone exposed.',
    details: [
      ['Compatibility', 'iPhone 17 Pro'],
      ['Finish', 'Silver'],
    ],
    url: 'https://arc.cc/products/arc-pulse-for-iphone-17-pro',
  },
  {
    id: 'artisan-hayate-otsu',
    name: 'Artisan Hayate Otsu',
    category: 'Mousepad',
    brand: 'Artisan',
    image: '/reviews/artisan-hayate-otsu-cutout.webp',
    alt: 'Artisan Hayate Otsu gaming mousepad',
    description:
      'A textured gaming mousepad designed to balance a quick glide with precise control.',
    details: [
      ['Surface', 'Hayate Otsu'],
      ['Type', 'Cloth mousepad'],
    ],
    url: 'https://artisan-jp.com/global/fx-hayate-otsu',
  },
  {
    id: 'airpods-max',
    name: 'AirPods Max',
    category: 'Headphones',
    brand: 'Apple',
    image: '/reviews/airpods-max-single.webp',
    alt: 'Apple AirPods Max in Space Gray',
    description:
      'Over-ear wireless headphones with Active Noise Cancellation and Transparency mode.',
    details: [
      ['Finish', 'Space Gray'],
      ['Design', 'Over-ear'],
    ],
    url: 'https://support.apple.com/en-us/111858',
  },
  {
    id: 'fitbit-air',
    name: 'Fitbit Air',
    category: 'Fitness tracker',
    brand: 'Google Fitbit',
    image: '/reviews/fitbit-air.webp',
    alt: 'Black Fitbit Air with an Obsidian band',
    description:
      'A screen-free fitness tracker for everyday activity and sleep tracking.',
    details: [
      ['Finish', 'Obsidian / black'],
      ['Type', 'Fitness tracker'],
    ],
    url: 'https://store.google.com/product/google_fitbit_air',
  },
  {
    id: 'dbrand-leather',
    name: 'dbrand Black Leather Skin',
    category: 'Laptop skin',
    brand: 'dbrand',
    image: '/reviews/dbrand-leather.webp',
    alt: 'MacBook Pro lid covered in dbrand black leather',
    description: 'A precision-cut leather skin for the MacBook Pro lid.',
    details: [
      ['Device', 'MacBook Pro'],
      ['Material', 'Real Black Leather'],
    ],
    url: 'https://dbrand.com/shop/skins/macbook-pro-14-2026-m5-skins?design=rl-blk',
  },
  {
    id: 'pulsar-superglide-black',
    name: 'Pulsar Superglide',
    category: 'Mousepad',
    brand: 'Pulsar',
    image: '/reviews/pulsar-superglide-black.png',
    alt: 'Black Pulsar Superglide glass mousepad',
    description: '',
    details: [],
    url: 'https://www.pulsar.gg/products/superglide-mousepad',
  },
  {
    id: 'steelseries-apex-pro-tkl',
    name: 'SteelSeries Apex Pro TKL',
    category: 'Keyboard',
    brand: 'SteelSeries',
    image: '/reviews/apex-pro-tkl-cutout.png',
    alt: 'Top view of the black SteelSeries Apex Pro TKL with RGB lighting',
    description: '',
    details: [],
    url: 'https://steelseries.com/gaming-keyboards/apex-pro-2023',
  },
  {
    id: 'razer-viper-mini',
    name: 'Razer Viper Mini',
    category: 'Mouse',
    brand: 'Razer',
    image: '/reviews/razer-viper-mini-clean.png',
    alt: 'Black Razer Viper Mini wired mouse',
    description: '',
    details: [],
    url: 'https://www.razer.com/gaming-mice/razer-viper-mini',
  },
  {
    id: 'logitech-g-pro-x-superlight',
    name: 'Logitech G Pro X Superlight',
    category: 'Mouse',
    brand: 'Logitech',
    image: '/reviews/g-pro-x-superlight-white.png',
    alt: 'White Logitech G Pro X Superlight mouse',
    description: '',
    details: [],
    url: 'https://www.logitechg.com/en-us/shop/p/pro-x-superlight-wireless-mouse',
  },
  {
    id: 'artisan-hien-red',
    name: 'Artisan Hien',
    category: 'Mousepad',
    brand: 'Artisan',
    image: '/reviews/artisan-hien-red-cutout.png',
    alt: 'Red Artisan Hien mousepad',
    description: '',
    details: [],
    url: 'https://artisan-jp.com/global/fx-hien',
  },
  {
    id: 'whoop-black',
    name: 'WHOOP',
    category: 'Fitness tracker',
    brand: 'WHOOP',
    image: '/reviews/whoop-black-cutout.png',
    alt: 'Black WHOOP fitness tracker and band',
    description: '',
    details: [],
    url: 'https://www.whoop.com/us/en/one/',
  },
] as const

export const softwareProducts = [
  {
    id: 'dia',
    name: 'Dia',
    category: 'Browser',
    platform: 'desktop',
    brand: 'The Browser Company',
    image: '/reviews/apps/dia.webp',
    alt: 'Dia app icon',
    description:
      'An AI browser with contextual assistance for the tabs you\u2019re working in.',
    details: [
      ['Category', 'Browser'],
      ['Features', 'AI assistance'],
    ],
    url: 'https://diabrowser.com',
    kind: 'software',
  },
  {
    id: 'arc',
    published: false,
    name: 'Arc Browser',
    category: 'Browser',
    platform: 'both',
    brand: 'The Browser Company',
    image: '/reviews/arc-search-icon.png',
    alt: 'Arc mobile app icon',
    description:
      'A browser built around Spaces, Profiles, and a sidebar for organizing your tabs.',
    details: [
      ['Category', 'Browser'],
      ['Features', 'Spaces & Profiles'],
    ],
    url: 'https://arc.net',
    kind: 'software',
  },
  {
    id: 'fl-studio',
    name: 'FL Studio',
    category: 'Music production',
    platform: 'desktop',
    brand: 'Image-Line',
    image: '/reviews/apps/fl-studio.webp',
    alt: 'FL Studio app icon',
    description:
      'A digital audio workstation for composing, recording, arranging, and mixing music.',
    details: [
      ['Category', 'Music production'],
      ['Features', 'Recording & mixing'],
    ],
    url: 'https://image-line.com',
    kind: 'software',
  },
  {
    id: 'raycast',
    name: 'Raycast',
    category: 'Productivity',
    platform: 'desktop',
    brand: 'Raycast',
    image: '/reviews/apps/raycast.webp',
    alt: 'Raycast app icon',
    description:
      'A keyboard-first launcher for searching, running commands, and working with extensions.',
    details: [
      ['Category', 'Productivity'],
      ['Features', 'Commands & extensions'],
    ],
    url: 'https://raycast.com',
    kind: 'software',
  },
  {
    id: 'zed',
    name: 'Zed',
    category: 'Code editor',
    platform: 'desktop',
    brand: 'Zed Industries',
    image: '/reviews/apps/zed.webp',
    alt: 'Zed app icon',
    description: 'A code editor with a focus on performance and collaboration.',
    details: [
      ['Category', 'Code editor'],
      ['Features', 'Code & collaboration'],
    ],
    url: 'https://zed.dev',
    kind: 'software',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'Notes',
    platform: 'both',
    brand: 'Obsidian',
    image: '/reviews/apps/obsidian.webp',
    alt: 'Obsidian app icon',
    description:
      'A Markdown workspace for local notes, linked ideas, and a personal knowledge base.',
    details: [
      ['Category', 'Notes'],
      ['Features', 'Markdown & backlinks'],
    ],
    url: 'https://obsidian.md',
    kind: 'software',
  },
  {
    id: 'warp',
    name: 'Warp',
    category: 'Terminal',
    platform: 'desktop',
    brand: 'Warp',
    image: '/reviews/apps/warp.webp',
    alt: 'Warp app icon',
    description:
      'A terminal with command blocks and AI assistance for working at the command line.',
    details: [
      ['Category', 'Terminal'],
      ['Features', 'Blocks & AI assistance'],
    ],
    url: 'https://warp.dev',
    kind: 'software',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    category: 'Code editor',
    platform: 'desktop',
    brand: 'Cursor',
    image: '/reviews/apps/cursor.webp',
    alt: 'Cursor app icon',
    description:
      'An AI code editor for writing, navigating, and editing a codebase.',
    details: [
      ['Category', 'Code editor'],
      ['Features', 'AI coding'],
    ],
    url: 'https://cursor.com',
    kind: 'software',
  },
  {
    id: 'hermes',
    name: 'Hermes',
    category: 'AI agent',
    platform: 'desktop',
    brand: 'Nous Research',
    image: '/reviews/apps/hermes.webp',
    alt: 'Hermes app icon',
    description:
      'An open-source AI agent with persistent memory and reusable skills.',
    details: [
      ['Category', 'AI agent'],
      ['Features', 'Memory & skills'],
    ],
    url: 'https://hermes-agent.nousresearch.com',
    kind: 'software',
  },
  {
    id: 'wispr-flow',
    name: 'Wispr Flow',
    category: 'Dictation',
    platform: 'both',
    brand: 'Wispr',
    image: '/reviews/apps/wispr-flow.webp',
    alt: 'Wispr Flow app icon',
    description:
      'Voice dictation that turns speech into text across your apps.',
    details: [
      ['Category', 'Dictation'],
      ['Features', 'Voice-to-text'],
    ],
    url: 'https://wisprflow.ai',
    kind: 'software',
  },
  {
    id: 'helium',
    published: true,
    name: 'Helium',
    category: 'Browser',
    platform: 'desktop',
    brand: 'imput',
    image: '/reviews/apps/helium.png',
    alt: 'Helium app icon',
    description: 'A privacy-focused browser with Chromium extension support.',
    details: [
      ['Category', 'Browser'],
      ['Features', 'Privacy & extensions'],
    ],
    url: 'https://helium.computer',
    kind: 'software',
  },
  {
    id: 'zen',
    name: 'Zen',
    category: 'Browser',
    platform: 'desktop',
    brand: 'Zen',
    image: '/reviews/apps/zen.webp',
    alt: 'Zen app icon',
    description:
      'A customizable browser with Workspaces, Compact Mode, and Split View.',
    details: [
      ['Category', 'Browser'],
      ['Features', 'Workspaces & split view'],
    ],
    url: 'https://zen-browser.app',
    kind: 'software',
  },
  {
    id: 'figma',
    name: 'Figma',
    category: 'Design tool',
    platform: 'both',
    brand: 'Figma',
    image: '/reviews/apps/figma.png',
    alt: 'Figma app icon',
    description: 'A collaborative design tool for interfaces and prototypes.',
    details: [['Category', 'Design tool']],
    url: 'https://www.figma.com',
    kind: 'software',
  },
  {
    id: 't3-code',
    name: 'T3 Code',
    category: 'AI coding agent',
    platform: 'desktop',
    brand: 'T3',
    image: '/reviews/apps/t3-code.png',
    alt: 'T3 Code app icon',
    description: 'A coding agent interface for working across local projects.',
    details: [['Category', 'AI coding agent']],
    url: 'https://t3.codes',
    kind: 'software',
  },
  {
    id: 'grok-bot',
    name: 'Grok Bot',
    category: 'AI agent',
    platform: 'both',
    brand: 'xAI',
    image: '/reviews/apps/grok-bot.webp',
    alt: 'Grok Bot app icon',
    description: 'AI teammates that work across websites and connected tools.',
    details: [['Category', 'AI agent']],
    url: 'https://x.ai/bot',
    kind: 'software',
  },
  {
    id: 'paper',
    name: 'Paper',
    category: 'Design tool',
    platform: 'desktop',
    brand: 'Paper',
    image: '/reviews/apps/paper.webp',
    alt: 'Paper design app icon',
    description: 'A design canvas that connects teams, code, and AI agents.',
    details: [['Category', 'Design tool']],
    url: 'https://paper.design',
    kind: 'software',
  },
  {
    id: 'bevel',
    published: false,
    name: 'Bevel',
    category: 'Health',
    platform: 'mobile',
    brand: 'Bevel',
    image: '/reviews/bevel-icon.png',
    alt: 'Bevel mobile app icon',
    description:
      'A health app for tracking recovery, sleep, activity, and nutrition.',
    details: [['Category', 'Health']],
    url: 'https://www.bevel.health',
    kind: 'software',
  },
  {
    id: 'flighty',
    published: false,
    name: 'Flighty',
    category: 'Travel',
    platform: 'both',
    brand: 'Flighty',
    image: '/reviews/flighty-icon.png',
    alt: 'Flighty app icon',
    description: 'A flight tracker with live updates and delay alerts.',
    details: [['Category', 'Travel']],
    url: 'https://flighty.com',
    kind: 'software',
  },
  {
    id: 'blackmagic-camera',
    published: false,
    name: 'Blackmagic Camera',
    category: 'Camera',
    platform: 'mobile',
    brand: 'Blackmagic Design',
    image: '/reviews/blackmagic-camera-icon.png',
    alt: 'Blackmagic Camera mobile app icon',
    description: 'A mobile camera app with professional video controls.',
    details: [['Category', 'Camera']],
    url: 'https://www.blackmagicdesign.com/products/blackmagiccamera',
    kind: 'software',
  },
  {
    id: 'ghostty',
    published: true,
    name: 'Ghostty',
    category: 'Terminal',
    platform: 'desktop',
    brand: 'Ghostty',
    image: '/reviews/apps/ghostty.webp',
    alt: 'Ghostty desktop app icon',
    description: 'A native terminal emulator for macOS and Linux.',
    details: [['Category', 'Terminal']],
    url: 'https://ghostty.org',
    kind: 'software',
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    category: 'AI coding agent',
    platform: 'desktop',
    brand: 'OpenCode',
    image: '/reviews/apps/opencode.webp',
    alt: 'OpenCode app icon',
    description: 'An open-source AI coding agent for desktop and terminal.',
    details: [['Category', 'AI coding agent']],
    url: 'https://opencode.ai',
    kind: 'software',
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    category: 'AI assistant',
    platform: 'both',
    brand: 'OpenAI',
    image: '/reviews/apps/chatgpt.webp',
    alt: 'ChatGPT app icon',
    description: 'An AI assistant for writing, learning, coding, and more.',
    details: [['Category', 'AI assistant']],
    url: 'https://chatgpt.com',
    kind: 'software',
  },
] as const

export const albums = [
  {
    id: 'femme-fatale',
    kind: 'album',
    name: 'femme fatale',
    category: 'Album',
    brand: 'skaiwater',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/83/3e/a7/833ea758-bf6b-a3a9-1f85-e856ff9102b6/612891189131.jpg/1200x1200bb.jpg',
    alt: 'femme fatale album cover by skaiwater',
    description: 'femme fatale by skaiwater.',
    details: [
      ['Released', 'August 31, 2026'],
      ['Tracks', '12'],
    ],
    url: 'https://music.apple.com/us/album/femme-fatale/6801310621?uo=4',
  },
  {
    id: 'empty-clip',
    kind: 'album',
    name: 'Empty Clip',
    category: 'EP',
    brand: 'Che',
    image:
      'https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02c11e6e1a986f03728f69e073',
    alt: 'Empty Clip EP cover by Che',
    description: 'Empty Clip by Che.',
    details: [
      ['Released', 'June 23, 2026'],
      ['Tracks', '5'],
    ],
    url: 'https://open.spotify.com/album/6sV9RQ72HZNZlBzzvkKl3S',
  },
  {
    id: 'backstage-hologram',
    kind: 'album',
    name: 'Backstage hologram',
    category: 'Album',
    brand: 'kuru',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/2b/a2/28/2ba228f7-2639-cc5b-fb05-efacdee40374/8398.jpg/1200x1200bb.jpg',
    alt: 'Backstage hologram album cover by kuru',
    description: 'Backstage hologram by kuru.',
    details: [
      ['Released', 'April 17, 2026'],
      ['Tracks', '15'],
    ],
    url: 'https://music.apple.com/us/album/backstage-hologram/1890530996?uo=4',
  },
  {
    id: 'suffer',
    kind: 'album',
    name: 'suffer',
    category: 'Album',
    brand: 'funeral',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/34/70/a3/3470a374-28cc-1399-3175-f1062e3c1c16/artwork.jpg/1200x1200bb.jpg',
    alt: 'suffer album cover by funeral',
    description: 'suffer by funeral.',
    details: [
      ['Released', 'October 31, 2025'],
      ['Tracks', '13'],
    ],
    url: 'https://music.apple.com/us/album/suffer/1848058839?uo=4',
  },
  {
    id: 'psykotic',
    kind: 'album',
    name: 'psykotic',
    category: 'Album',
    brand: 'OsamaSon',
    image: '/reviews/albums/psykotic.webp',
    alt: 'psykotic album cover by OsamaSon',
    description: 'psykotic by OsamaSon.',
    details: [
      ['Released', 'October 10, 2025'],
      ['Tracks', '17'],
    ],
    url: 'https://music.apple.com/us/album/psykotic/1844725594?uo=4',
  },
  {
    id: 'yall',
    kind: 'album',
    name: 'Y’all',
    category: 'Album',
    brand: 'glaive',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/4e/6f/60/4e6f60d5-704f-ae28-15cc-f51f0aa1106d/663918508169.jpg/1200x1200bb.jpg',
    alt: 'Y’all album cover by glaive',
    description: 'Y’all by glaive.',
    details: [
      ['Released', 'September 25, 2025'],
      ['Tracks', '16'],
    ],
    url: 'https://music.apple.com/us/album/yall/1838587274?uo=4',
  },
  {
    id: 'i-love-my-computer',
    kind: 'album',
    name: 'I Love My Computer',
    category: 'Album',
    brand: 'Ninajirachi',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/51/41/9c/51419c3f-dce3-5072-eb94-fc453f6fdb87/199350974793.jpg/1200x1200bb.jpg',
    alt: 'I Love My Computer album cover by Ninajirachi',
    description: 'I Love My Computer by Ninajirachi.',
    details: [
      ['Released', 'August 8, 2025'],
      ['Tracks', '12'],
    ],
    url: 'https://music.apple.com/us/album/i-love-my-computer/1824602984?uo=4',
  },
  {
    id: 'stay-true-forever',
    kind: 'album',
    name: 'Stay true forever',
    category: 'Album',
    brand: 'kuru',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/b6/e9/18/b6e918c9-2c84-1f24-4cf7-89606325c180/193436428460_kurucover.jpg/1200x1200bb.jpg',
    alt: 'Stay true forever album cover by kuru',
    description: 'Stay true forever by kuru.',
    details: [
      ['Released', 'May 23, 2025'],
      ['Tracks', '18'],
    ],
    url: 'https://music.apple.com/us/album/stay-true-forever/1815549288?uo=4',
  },
  {
    id: 'unmusique',
    kind: 'album',
    name: 'Unmusique',
    category: 'Album',
    brand: 'Lucy Bedroque',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/b4/e0/2b/b4e02bd9-ad8f-0bdb-483a-bf91762d49d0/193436426565_Untica.jpg/1200x1200bb.jpg',
    alt: 'Unmusique album cover by Lucy Bedroque',
    description: 'Unmusique by Lucy Bedroque.',
    details: [
      ['Released', 'May 16, 2025'],
      ['Tracks', '17'],
    ],
    url: 'https://music.apple.com/us/album/unmusique/1812489371?uo=4',
  },
  {
    id: 'star',
    kind: 'album',
    name: 'star',
    category: 'Album',
    brand: '2hollis',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/3a/da/c0/3adac065-136d-d93c-edc8-fdfa4a744b7f/25UMGIM44740.rgb.jpg/1200x1200bb.jpg',
    alt: 'star album cover by 2hollis',
    description: 'star by 2hollis.',
    details: [
      ['Released', 'April 4, 2025'],
      ['Tracks', '15'],
    ],
    url: 'https://music.apple.com/us/album/star/1803726233?uo=4',
  },
  {
    id: 'revengeseekerz',
    kind: 'album',
    name: 'Revengeseekerz',
    category: 'Album',
    brand: 'Jane Remover',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/18/cf/f6/18cff6df-c7b6-0ca1-8067-83743f6c1f8a/193436418720_coverGriffinMcMahon.jpg/1200x1200bb.jpg',
    alt: 'Revengeseekerz album cover by Jane Remover',
    description: 'Revengeseekerz by Jane Remover.',
    details: [
      ['Released', 'April 4, 2025'],
      ['Tracks', '12'],
    ],
    url: 'https://music.apple.com/us/album/revengeseekerz/1800020675?uo=4',
  },
  {
    id: 'museum-music',
    kind: 'album',
    name: 'Museum Music',
    category: 'Album',
    brand: 'Edward Skeletrix',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/ce/b6/29/ceb629ca-d796-063b-e592-c13bea553bcc/24SYMIM16944.rgb.jpg/1200x1200bb.jpg',
    alt: 'Museum Music album cover by Edward Skeletrix',
    description: 'Museum Music by Edward Skeletrix.',
    details: [
      ['Released', 'January 1, 2025'],
      ['Tracks', '15'],
    ],
    url: 'https://music.apple.com/us/album/museum-music/1784809548?uo=4',
  },
  {
    id: 'suicideseason',
    kind: 'album',
    name: 'suicideseason',
    category: 'Album',
    brand: 'funeral',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/87/34/57/87345780-cc3c-df59-83d3-45fa44b823bd/artwork.jpg/1200x1200bb.jpg',
    alt: 'suicideseason album cover by funeral',
    description: 'suicideseason by funeral.',
    details: [
      ['Released', 'November 8, 2024'],
      ['Tracks', '11'],
    ],
    url: 'https://music.apple.com/us/album/suicideseason/1776697619?uo=4',
  },
  {
    id: 'scrapyard',
    kind: 'album',
    name: 'Scrapyard',
    category: 'Album',
    brand: 'Quadeca',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/2c/d8/a4/2cd8a455-be1b-27c0-810a-05fb226914c7/193436371186.png/1200x1200bb.jpg',
    alt: 'Scrapyard album cover by Quadeca',
    description: 'Scrapyard by Quadeca.',
    details: [
      ['Released', 'February 16, 2024'],
      ['Tracks', '15'],
    ],
    url: 'https://music.apple.com/us/album/scrapyard/1745245323?uo=4',
  },
  {
    id: 'lucy-bedroque-c',
    kind: 'album',
    name: 'c',
    category: 'Album',
    brand: 'Lucy Bedroque',
    image: '/reviews/albums/lucy-bedroque-c.webp',
    alt: 'c album cover by Lucy Bedroque',
    description: 'c by Lucy Bedroque.',
    details: [
      ['Released', 'September 18, 2026'],
      ['Tracks', '15'],
    ],
    url: 'https://music.apple.com/us/album/c/6811154278?uo=4',
  },
  {
    id: 'god-save-the-three',
    kind: 'album',
    name: 'God Save The Three',
    category: 'Album',
    brand: 'glaive & kurtains',
    image: '/reviews/albums/god-save-the-three.webp',
    alt: 'God Save The Three album cover by glaive & kurtains',
    description: 'God Save The Three by glaive & kurtains.',
    details: [
      ['Released', 'May 8, 2026'],
      ['Tracks', '12'],
    ],
    url: 'https://music.apple.com/us/album/god-save-the-three/1895286099?uo=4',
  },
  {
    id: 'exiler',
    kind: 'album',
    name: 'EXILER',
    category: 'Album',
    brand: 'funeral',
    image: '/reviews/albums/exiler.webp',
    alt: 'EXILER album cover by funeral',
    description: 'EXILER by funeral.',
    details: [
      ['Released', 'May 8, 2026'],
      ['Tracks', '13'],
    ],
    url: 'https://music.apple.com/us/album/exiler/1896181544?uo=4',
  },
  {
    id: 'underscores-u',
    kind: 'album',
    name: 'U',
    category: 'Album',
    brand: 'underscores',
    image: '/reviews/albums/underscores-u.webp',
    alt: 'U album cover by underscores',
    description: 'U by underscores.',
    details: [
      ['Released', 'March 20, 2026'],
      ['Tracks', '9'],
    ],
    url: 'https://music.apple.com/us/album/u/1878382378?uo=4',
  },
  {
    id: 'early-life-crisis',
    kind: 'album',
    name: 'early life crisis',
    category: 'Album',
    brand: 'Nettspend',
    image: '/reviews/albums/early-life-crisis.webp',
    alt: 'early life crisis album cover by Nettspend',
    description: 'early life crisis by Nettspend.',
    details: [
      ['Released', 'March 6, 2026'],
      ['Tracks', '21'],
    ],
    url: 'https://music.apple.com/us/album/early-life-crisis/1882856669?uo=4',
  },
  {
    id: 'strung-out-symphony',
    kind: 'album',
    name: 'Strung Out Symphony',
    category: 'Album',
    brand: 'aldn',
    image: '/reviews/albums/strung-out-symphony.webp',
    alt: 'Strung Out Symphony album cover by aldn',
    description: 'Strung Out Symphony by aldn.',
    details: [
      ['Released', 'October 3, 2025'],
      ['Tracks', '14'],
    ],
    url: 'https://music.apple.com/us/album/strung-out-symphony/1796021246?uo=4',
  },
  {
    id: 'rest-in-bass-encore',
    kind: 'album',
    name: 'REST IN BASS: ENCORE',
    category: 'Album',
    brand: 'Che',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/d9/06/f9/d906f9b7-c2cc-ff7a-f2eb-c58b427c7473/810129965797.jpg/1200x1200bb.jpg',
    alt: 'REST IN BASS: ENCORE album cover by Che',
    description: 'REST IN BASS: ENCORE by Che.',
    details: [
      ['Released', 'December 25, 2025'],
      ['Tracks', '32'],
    ],
    url: 'https://music.apple.com/us/album/rest-in-bass-encore/1860438163?uo=4',
  },
  {
    id: 'vanisher-horizon-scraper',
    kind: 'album',
    name: 'Vanisher, Horizon Scraper',
    category: 'Album',
    brand: 'Quadeca',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/c3/5f/da/c35fda1f-ad32-33ec-8f38-6756ef88a6c4/1248.jpg/1200x1200bb.jpg',
    alt: 'Vanisher, Horizon Scraper album cover by Quadeca',
    description: 'Vanisher, Horizon Scraper by Quadeca.',
    details: [
      ['Released', 'July 25, 2025'],
      ['Tracks', '14'],
    ],
    url: 'https://music.apple.com/us/album/vanisher-horizon-scraper/1825601354?uo=4',
  },
  {
    id: 'half-blood',
    kind: 'album',
    name: 'Half Blood',
    category: 'Album',
    brand: 'slayr',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/41/c2/66/41c266af-579e-60d0-c07a-cbf5f089797b/196874378830.jpg/1200x1200bb.jpg',
    alt: 'Half Blood album cover by slayr',
    description: 'Half Blood by slayr.',
    details: [
      ['Released', 'November 5, 2025'],
      ['Tracks', '11'],
    ],
    url: 'https://music.apple.com/us/album/half-blood/1896351634?uo=4',
  },
  {
    id: 'the-world-ends-with-you',
    kind: 'album',
    name: 'THE WORLD ENDS WITH YOU',
    category: 'Album',
    brand: 'whereisreef',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/e0/fe/de/e0fededa-691a-30e7-7ef5-4ee71924b62a/artwork.jpg/1200x1200bb.jpg',
    alt: 'THE WORLD ENDS WITH YOU album cover by whereisreef',
    description: 'THE WORLD ENDS WITH YOU by whereisreef.',
    details: [
      ['Released', 'December 5, 2025'],
      ['Tracks', '14'],
    ],
    url: 'https://music.apple.com/us/album/the-world-ends-with-you/1857818743?uo=4',
  },
  {
    id: 'the-world-starts-with-us',
    kind: 'album',
    name: 'THE WORLD STARTS WITH US',
    category: 'Album',
    brand: 'whereisreef',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/f9/98/cb/f998cbda-bc3a-782e-46e4-79e33e549c2d/artwork.jpg/1200x1200bb.jpg',
    alt: 'THE WORLD STARTS WITH US album cover by whereisreef',
    description: 'THE WORLD STARTS WITH US by whereisreef.',
    details: [
      ['Released', 'March 14, 2026'],
      ['Tracks', '9'],
    ],
    url: 'https://music.apple.com/us/album/the-world-starts-with-us/1886515421?uo=4',
  },
  {
    id: 'for-the-rest-of-your-life',
    kind: 'album',
    name: 'for the rest of your life',
    category: 'Album',
    brand: 'twikipedia',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/84/10/1c/84101c78-3d29-bd0f-a172-ad8f4f3f1563/artwork.jpg/1200x1200bb.jpg',
    alt: 'for the rest of your life album cover by twikipedia',
    description: 'for the rest of your life by twikipedia.',
    details: [
      ['Released', 'May 10, 2024'],
      ['Tracks', '13'],
    ],
    url: 'https://music.apple.com/us/album/for-the-rest-of-your-life/1743125079?uo=4',
  },
  {
    id: 'a-tool-for-expression',
    kind: 'album',
    name: 'A TOOL FOR EXPRESSION',
    category: 'Album',
    brand: 'Dani Kiyoko',
    image:
      'https://image-cdn-fa.spotifycdn.com/image/ab67616d0000b2738285ed71e2fcc19832109ee2',
    alt: 'A TOOL FOR EXPRESSION album cover by Dani Kiyoko',
    description: 'A TOOL FOR EXPRESSION by Dani Kiyoko.',
    details: [
      ['Released', 'June 19, 2026'],
      ['Tracks', '21'],
    ],
    url: 'https://open.spotify.com/album/4kIexwH7gt7KpegeAiVhVz',
  },
  {
    id: 'things-i-forgot-about',
    kind: 'album',
    name: 'things i forgot about',
    category: 'Album',
    brand: 'ovine hall',
    image:
      'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/04/3f/44/043f4475-6869-9be3-61f5-83136791fb44/artwork.jpg/1200x1200bb.jpg',
    alt: 'things i forgot about album cover by ovine hall',
    description: 'things i forgot about by ovine hall.',
    details: [
      ['Released', 'December 10, 2025'],
      ['Tracks', '7'],
    ],
    url: 'https://music.apple.com/us/album/things-i-forgot-about/1860431210?uo=4',
  },
  {
    id: 'protagonist-bleood',
    kind: 'album',
    name: 'PROTAGONIST',
    category: 'Album',
    brand: 'bleood',
    image:
      'https://image-cdn-fa.spotifycdn.com/image/ab67616d0000b2738eabe1fe40434866f52fea76',
    alt: 'PROTAGONIST album cover by bleood',
    description: 'PROTAGONIST by bleood.',
    details: [
      ['Released', 'May 14, 2026'],
      ['Tracks', '9'],
    ],
    url: 'https://open.spotify.com/album/7eYNXOje1eRZYUtiseHCVQ',
  },
  {
    id: 'status-update-music',
    kind: 'album',
    name: 'status update music',
    category: 'Album',
    brand: 'leroy',
    image: '/reviews/albums/status-update-music.jpg',
    alt: 'status update music album cover by leroy',
    description: 'status update music by leroy.',
    details: [
      ['Released', 'May 14, 2026'],
      ['Tracks', '15'],
    ],
    url: 'https://janeremover.bandcamp.com/album/status-update-music',
  },
] as const
