export const hardwareProducts = [
  {
    id: 'wooting-60he',
    name: 'Wooting 60HE+',
    category: 'Keyboard',
    brand: 'Wooting',
    image: '/reviews/wooting-60he.webp',
    alt: 'Wooting 60HE+ black keyboard with its yellow Take Control strap',
    description:
      'A compact analog keyboard built around adjustable actuation and Rapid Trigger.',
    details: [
      ['Layout', '60%'],
      ['Switches', 'Lekker magnetic'],
    ],
    url: 'https://wooting.io/wooting-60he',
  },
  {
    id: 'finalmouse-ulx',
    name: 'Finalmouse ULX Phantom',
    category: 'Mouse',
    brand: 'Finalmouse',
    image: '/reviews/finalmouse-ulx-light-cutout.webp',
    alt: 'Finalmouse UltralightX Phantom mouse viewed from above',
    description:
      'The Phantom edition of Finalmouse’s UltralightX gaming mouse.',
    details: [
      ['Series', 'UltralightX'],
      ['Edition', 'Phantom'],
    ],
    url: 'https://finalmouse.com/pages/mice',
  },
  {
    id: 'sennheiser-hd6xx',
    name: 'Sennheiser HD 6XX',
    category: 'Headphones',
    brand: 'Sennheiser × Massdrop',
    image: '/reviews/sennheiser-hd6xx-cutout.webp',
    alt: 'Sennheiser HD 6XX over-ear headphones in midnight blue',
    description:
      'A community collaboration from the HD 600 family, finished in midnight blue.',
    details: [
      ['Cable', 'Detachable · 1.8 m'],
      ['Connector', '3.5 mm + 6.35 mm adapter'],
    ],
    url: 'https://us.sennheiser-hearing.com/products/hd-6xx',
  },
  {
    id: 'wallhack-sp004',
    name: 'WALLHACK SP-004',
    category: 'Mousepad',
    brand: 'WALLHACK',
    image: '/reviews/skypad-sp004.png',
    alt: 'Black WALLHACK SP-004 glass mousepad viewed from above',
    description: 'A micro-etched glass surface with a full silicone base.',
    details: [
      ['Surface', 'Silicate glass'],
      ['Dimensions', '490 × 430 × 3.9 mm'],
    ],
    url: 'https://wallhack.com/products/sp-004-black',
  },
  {
    id: 'jds-atom-2',
    name: 'JDS Labs Atom 2 Stack',
    category: 'Amp + DAC',
    brand: 'JDS Labs',
    image: '/reviews/jds-atom-2-cutout.webp',
    alt: 'JDS Labs Atom Amp 2 and Atom DAC 2 desktop audio stack',
    description:
      'A desktop audio pair combining the Atom Amp 2 headphone amplifier and Atom DAC 2.',
    details: [
      ['Amplifier', 'Atom Amp 2'],
      ['DAC', 'Atom DAC 2'],
    ],
    url: 'https://jdslabs.com/product/atom-amp-2/',
  },
  {
    id: 'iphone-17-pro',
    name: 'iPhone 17 Pro',
    category: 'Phone',
    brand: 'Apple',
    image: '/reviews/iphone-17-pro-silver.webp',
    alt: 'Silver Apple iPhone 17 Pro',
    description:
      'Apple’s Pro iPhone, with a triple-camera system and an aluminum unibody design.',
    details: [
      ['Family', 'iPhone 17'],
      ['Finish', 'Silver'],
    ],
    url: 'https://www.apple.com/newsroom/2025/09/apple-unveils-iphone-17-pro-and-iphone-17-pro-max/',
  },
  {
    id: 'dt-990-pro',
    name: 'Beyerdynamic DT 990 Pro',
    category: 'Headphones',
    brand: 'Beyerdynamic',
    image: '/reviews/dt-990-pro.png',
    alt: 'Beyerdynamic DT 990 Pro open-back headphones',
    description:
      'Open-back studio headphones with an over-ear fit and replaceable ear pads.',
    details: [
      ['Design', 'Open-back'],
      ['Fit', 'Over-ear'],
    ],
    url: 'https://north-america.beyerdynamic.com/p/dt-990-pro',
  },
  {
    id: 'ikea-idasen',
    name: 'IKEA IDÅSEN',
    category: 'Desk',
    brand: 'IKEA',
    image: '/reviews/ikea-idasen-black.webp',
    alt: 'IKEA IDÅSEN desk with a black tabletop and dark gray legs',
    description: 'A workspace desk from IKEA’s IDÅSEN office furniture series.',
    details: [
      ['Series', 'IDÅSEN'],
      ['Finish', 'Black / dark gray'],
    ],
    url: 'https://www.ikea.com/us/en/cat/idasen-system-47424/',
  },
  {
    id: 'steelcase-leap',
    name: 'Steelcase Leap V2',
    category: 'Chair',
    brand: 'Steelcase',
    image: '/reviews/steelcase-leap-black.webp',
    alt: 'Black Steelcase Leap V2 office chair',
    description:
      'An adjustable office chair with a flexible backrest designed to follow your movement.',
    details: [
      ['Model', 'Leap V2'],
      ['Finish', 'Black'],
    ],
    url: 'https://www.steelcase.com/products/office-chairs/leap/',
  },
  {
    id: 'macbook-pro-m5',
    name: 'MacBook Pro M5',
    category: 'Laptop',
    brand: 'Apple',
    image: '/reviews/macbook-pro-space-black-cutout.png',
    alt: 'Space Black Apple 14-inch MacBook Pro with M5, viewed from the front',
    description: 'The 14-inch MacBook Pro powered by Apple’s M5 chip.',
    details: [
      ['Chip', 'Apple M5'],
      ['Display', '14-inch Liquid Retina XDR'],
    ],
    url: 'https://www.apple.com/newsroom/2025/10/apple-unveils-new-14-inch-macbook-pro-powered-by-the-m5-chip/',
  },
  {
    id: 'arc-pulse',
    name: 'Arc Pulse',
    category: 'Phone case',
    brand: 'Arc',
    image: '/reviews/arc-pulse-silver.webp',
    alt: 'Silver Arc Pulse bumper case fitted to an iPhone 17 Pro',
    description:
      'A minimal two-piece phone case that leaves the back of the iPhone exposed.',
    details: [
      ['Compatibility', 'iPhone 17 Pro'],
      ['Finish', 'Silver'],
    ],
    url: 'https://arc.cc/products/arc-pulse-for-iphone-17-pro',
  },
  {
    id: 'artisan-hayate-otsu',
    name: 'Artisan Hayate Otsu',
    category: 'Mousepad',
    brand: 'Artisan',
    image: '/reviews/artisan-hayate-otsu-cutout.webp',
    alt: 'Artisan Hayate Otsu gaming mousepad',
    description:
      'A textured gaming mousepad designed to balance a quick glide with precise control.',
    details: [
      ['Surface', 'Hayate Otsu'],
      ['Type', 'Cloth mousepad'],
    ],
    url: 'https://artisan-jp.com/global/fx-hayate-otsu',
  },
  {
    id: 'airpods-max',
    name: 'AirPods Max',
    category: 'Headphones',
    brand: 'Apple',
    image: '/reviews/airpods-max-single.webp',
    alt: 'Apple AirPods Max in Space Gray',
    description:
      'Over-ear wireless headphones with Active Noise Cancellation and Transparency mode.',
    details: [
      ['Finish', 'Space Gray'],
      ['Design', 'Over-ear'],
    ],
    url: 'https://support.apple.com/en-us/111858',
  },
  {
    id: 'fitbit-air',
    name: 'Fitbit Air',
    category: 'Fitness tracker',
    brand: 'Google Fitbit',
    image: '/reviews/fitbit-air.webp',
    alt: 'Black Fitbit Air with an Obsidian band',
    description:
      'A screen-free fitness tracker for everyday activity and sleep tracking.',
    details: [
      ['Finish', 'Obsidian / black'],
      ['Type', 'Fitness tracker'],
    ],
    url: 'https://store.google.com/product/google_fitbit_air',
  },
  {
    id: 'dbrand-leather',
    name: 'dbrand Black Leather Skin',
    category: 'Laptop skin',
    brand: 'dbrand',
    image: '/reviews/dbrand-leather.webp',
    alt: 'MacBook Pro lid covered in dbrand black leather',
    description: 'A precision-cut leather skin for the MacBook Pro lid.',
    details: [
      ['Device', 'MacBook Pro'],
      ['Material', 'Real Black Leather'],
    ],
    url: 'https://dbrand.com/shop/skins/macbook-pro-14-2026-m5-skins?design=rl-blk',
  },
  {
    id: 'pulsar-superglide-black',
    name: 'Pulsar Superglide',
    category: 'Mousepad',
    brand: 'Pulsar',
    image: '/reviews/pulsar-superglide-black.png',
    alt: 'Black Pulsar Superglide glass mousepad',
    description: '',
    details: [],
    url: 'https://www.pulsar.gg/products/superglide-mousepad',
  },
  {
    id: 'steelseries-apex-pro-tkl',
    name: 'SteelSeries Apex Pro TKL',
    category: 'Keyboard',
    brand: 'SteelSeries',
    image: '/reviews/apex-pro-tkl-side.png',
    alt: 'Side view of the black SteelSeries Apex Pro TKL with wrist rest',
    description: '',
    details: [],
    url: 'https://steelseries.com/gaming-keyboards/apex-pro-2023',
  },
  {
    id: 'razer-viper-mini',
    name: 'Razer Viper Mini',
    category: 'Mouse',
    brand: 'Razer',
    image: '/reviews/razer-viper-mini-clean.png',
    alt: 'Black Razer Viper Mini wired mouse',
    description: '',
    details: [],
    url: 'https://www.razer.com/gaming-mice/razer-viper-mini',
  },
  {
    id: 'logitech-g-pro-x-superlight',
    name: 'Logitech G Pro X Superlight',
    category: 'Mouse',
    brand: 'Logitech',
    image: '/reviews/g-pro-x-superlight-white.png',
    alt: 'White Logitech G Pro X Superlight mouse',
    description: '',
    details: [],
    url: 'https://www.logitechg.com/en-us/shop/p/pro-x-superlight-wireless-mouse',
  },
  {
    id: 'artisan-hien-red',
    name: 'Artisan Hien',
    category: 'Mousepad',
    brand: 'Artisan',
    image: '/reviews/artisan-hien-red-cutout.png',
    alt: 'Red Artisan Hien mousepad',
    description: '',
    details: [],
    url: 'https://artisan-jp.com/global/fx-hien',
  },
  {
    id: 'whoop-black',
    name: 'WHOOP',
    category: 'Fitness tracker',
    brand: 'WHOOP',
    image: '/reviews/whoop-black-cutout.png',
    alt: 'Black WHOOP fitness tracker and band',
    description: '',
    details: [],
    url: 'https://www.whoop.com/us/en/one/',
  },
] as const

export const softwareProducts = [
  {
    id: 'dia',
    name: 'Dia Browser',
    category: 'Browser',
    brand: 'The Browser Company',
    image: '/reviews/dia-icon.webp',
    alt: 'Dia Browser app icon',
    description:
      'An AI browser with contextual assistance for the tabs you\u2019re working in.',
    details: [
      ['Category', 'Browser'],
      ['Features', 'AI assistance'],
    ],
    url: 'https://diabrowser.com',
    kind: 'software',
  },
  {
    id: 'arc',
    name: 'Arc Browser',
    category: 'Browser',
    brand: 'The Browser Company',
    image: '/reviews/arc-official-icon.webp',
    alt: 'Arc Browser app icon',
    description:
      'A browser built around Spaces, Profiles, and a sidebar for organizing your tabs.',
    details: [
      ['Category', 'Browser'],
      ['Features', 'Spaces & Profiles'],
    ],
    url: 'https://arc.net',
    kind: 'software',
  },
  {
    id: 'fl-studio',
    name: 'FL Studio',
    category: 'Music production',
    brand: 'Image-Line',
    image: '/reviews/fl-studio-icon.webp',
    alt: 'FL Studio app icon',
    description:
      'A digital audio workstation for composing, recording, arranging, and mixing music.',
    details: [
      ['Category', 'Music production'],
      ['Features', 'Recording & mixing'],
    ],
    url: 'https://image-line.com',
    kind: 'software',
  },
  {
    id: 'raycast',
    name: 'Raycast',
    category: 'Productivity',
    brand: 'Raycast',
    image: '/reviews/raycast-icon.webp',
    alt: 'Raycast app icon',
    description:
      'A keyboard-first launcher for searching, running commands, and working with extensions.',
    details: [
      ['Category', 'Productivity'],
      ['Features', 'Commands & extensions'],
    ],
    url: 'https://raycast.com',
    kind: 'software',
  },
  {
    id: 'zed',
    name: 'Zed IDE',
    category: 'Code editor',
    brand: 'Zed Industries',
    image: '/reviews/zed-icon.webp',
    alt: 'Zed IDE app icon',
    description: 'A code editor with a focus on performance and collaboration.',
    details: [
      ['Category', 'Code editor'],
      ['Features', 'Code & collaboration'],
    ],
    url: 'https://zed.dev',
    kind: 'software',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'Notes',
    brand: 'Obsidian',
    image: '/reviews/obsidian-icon.webp',
    alt: 'Obsidian app icon',
    description:
      'A Markdown workspace for local notes, linked ideas, and a personal knowledge base.',
    details: [
      ['Category', 'Notes'],
      ['Features', 'Markdown & backlinks'],
    ],
    url: 'https://obsidian.md',
    kind: 'software',
  },
  {
    id: 'warp',
    name: 'Warp Terminal',
    category: 'Terminal',
    brand: 'Warp',
    image: '/reviews/warp-icon.webp',
    alt: 'Warp Terminal app icon',
    description:
      'A terminal with command blocks and AI assistance for working at the command line.',
    details: [
      ['Category', 'Terminal'],
      ['Features', 'Blocks & AI assistance'],
    ],
    url: 'https://warp.dev',
    kind: 'software',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    category: 'Code editor',
    brand: 'Cursor',
    image: '/reviews/cursor-icon.webp',
    alt: 'Cursor app icon',
    description:
      'An AI code editor for writing, navigating, and editing a codebase.',
    details: [
      ['Category', 'Code editor'],
      ['Features', 'AI coding'],
    ],
    url: 'https://cursor.com',
    kind: 'software',
  },
  {
    id: 'hermes',
    name: 'Hermes',
    category: 'AI agent',
    brand: 'Nous Research',
    image: '/reviews/hermes-icon.webp',
    alt: 'Hermes app icon',
    description:
      'An open-source AI agent with persistent memory and reusable skills.',
    details: [
      ['Category', 'AI agent'],
      ['Features', 'Memory & skills'],
    ],
    url: 'https://hermes-agent.nousresearch.com',
    kind: 'software',
  },
  {
    id: 'wispr-flow',
    name: 'Wispr Flow',
    category: 'Dictation',
    brand: 'Wispr',
    image: '/reviews/wispr-flow-icon.webp',
    alt: 'Wispr Flow app icon',
    description:
      'Voice dictation that turns speech into text across your apps.',
    details: [
      ['Category', 'Dictation'],
      ['Features', 'Voice-to-text'],
    ],
    url: 'https://wisprflow.ai',
    kind: 'software',
  },
  {
    id: 'helium',
    name: 'Helium Browser',
    category: 'Browser',
    brand: 'imput',
    image: '/reviews/helium-icon.webp',
    alt: 'Helium Browser app icon',
    description: 'A privacy-focused browser with Chromium extension support.',
    details: [
      ['Category', 'Browser'],
      ['Features', 'Privacy & extensions'],
    ],
    url: 'https://helium.computer',
    kind: 'software',
  },
  {
    id: 'zen',
    name: 'Zen Browser',
    category: 'Browser',
    brand: 'Zen',
    image: '/reviews/zen-icon.webp',
    alt: 'Zen Browser app icon',
    description:
      'A customizable browser with Workspaces, Compact Mode, and Split View.',
    details: [
      ['Category', 'Browser'],
      ['Features', 'Workspaces & split view'],
    ],
    url: 'https://zen-browser.app',
    kind: 'software',
  },
] as const

export const albums = [
  {
    id: 'lucy-bedroque-c',
    kind: 'album',
    name: 'c',
    category: 'Album',
    brand: 'Lucy Bedroque',
    image: '/reviews/albums/lucy-bedroque-c.webp',
    alt: 'c album cover by Lucy Bedroque',
    description: 'c by Lucy Bedroque.',
    details: [
      ['Released', 'September 18, 2026'],
      ['Tracks', '15'],
    ],
    url: 'https://music.apple.com/us/album/c/6811154278?uo=4',
  },
  {
    id: 'god-save-the-three',
    kind: 'album',
    name: 'God Save The Three',
    category: 'Album',
    brand: 'glaive & kurtains',
    image: '/reviews/albums/god-save-the-three.webp',
    alt: 'God Save The Three album cover by glaive & kurtains',
    description: 'God Save The Three by glaive & kurtains.',
    details: [
      ['Released', 'May 8, 2026'],
      ['Tracks', '12'],
    ],
    url: 'https://music.apple.com/us/album/god-save-the-three/1895286099?uo=4',
  },
  {
    id: 'exiler',
    kind: 'album',
    name: 'EXILER',
    category: 'Album',
    brand: 'funeral',
    image: '/reviews/albums/exiler.webp',
    alt: 'EXILER album cover by funeral',
    description: 'EXILER by funeral.',
    details: [
      ['Released', 'May 8, 2026'],
      ['Tracks', '13'],
    ],
    url: 'https://music.apple.com/us/album/exiler/1896181544?uo=4',
  },
  {
    id: 'underscores-u',
    kind: 'album',
    name: 'U',
    category: 'Album',
    brand: 'underscores',
    image: '/reviews/albums/underscores-u.webp',
    alt: 'U album cover by underscores',
    description: 'U by underscores.',
    details: [
      ['Released', 'March 20, 2026'],
      ['Tracks', '9'],
    ],
    url: 'https://music.apple.com/us/album/u/1878382378?uo=4',
  },
  {
    id: 'early-life-crisis',
    kind: 'album',
    name: 'early life crisis',
    category: 'Album',
    brand: 'Nettspend',
    image: '/reviews/albums/early-life-crisis.webp',
    alt: 'early life crisis album cover by Nettspend',
    description: 'early life crisis by Nettspend.',
    details: [
      ['Released', 'March 6, 2026'],
      ['Tracks', '21'],
    ],
    url: 'https://music.apple.com/us/album/early-life-crisis/1882856669?uo=4',
  },
  {
    id: 'strung-out-symphony',
    kind: 'album',
    name: 'Strung Out Symphony',
    category: 'Album',
    brand: 'aldn',
    image: '/reviews/albums/strung-out-symphony.webp',
    alt: 'Strung Out Symphony album cover by aldn',
    description: 'Strung Out Symphony by aldn.',
    details: [
      ['Released', 'October 3, 2025'],
      ['Tracks', '14'],
    ],
    url: 'https://music.apple.com/us/album/strung-out-symphony/1796021246?uo=4',
  },
] as const
